["cloud.google.com/go"]
  sumVersion = "v0.45.1"
  ["cloud.google.com/go".fetch]
    type = "git"
    url = "https://github.com/googleapis/google-cloud-go"
    rev = "d1af076dc3f6a314e9dd6610fe83b0f7afaff6d6"
    sha256 = "18jcrm504yxxbrkb7vxzia7awc8yr0vb0hsddwvqk15c1rgi7ivj"

["cloud.google.com/go/bigquery"]
  sumVersion = "v1.0.1"
  relPath = "bigquery"
  ["cloud.google.com/go/bigquery".fetch]
    type = "git"
    url = "https://github.com/googleapis/google-cloud-go"
    rev = "63c28c0124777c34a3bca5876d3c0965ac730d3b"
    sha256 = "1gnvs0q96l37z0ypw426b590jsihn459scdzb0g8vr2c8lwkcrmh"

["cloud.google.com/go/datastore"]
  sumVersion = "v1.0.0"
  relPath = "datastore"
  ["cloud.google.com/go/datastore".fetch]
    type = "git"
    url = "https://github.com/googleapis/google-cloud-go"
    rev = "c5d562bdb35850f11d6a275d85ab8535265e9821"
    sha256 = "0d7ikvbyasifhbxgc2gw97zqc27ihi9a22wdywh5gw2cwjwpw5gi"

["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/BurntSushi/xgb"]
  sumVersion = "v0.0.0-20160522181843-27f122750802"
  ["github.com/BurntSushi/xgb".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/xgb"
    rev = "27f122750802c950b2c869a5b63dafcf590ced95"
    sha256 = "18lp2x8f5bljvlz0r7xn744f0c9rywjsb9ifiszqqdcpwhsa0kvj"

["github.com/aws/aws-sdk-go"]
  sumVersion = "v1.15.78"
  ["github.com/aws/aws-sdk-go".fetch]
    type = "git"
    url = "https://github.com/aws/aws-sdk-go"
    rev = "5ebc7a404e942062fd3aa7ff50975498716eb990"
    sha256 = "12lwccppdg6chmjdjd7yj73bqhrshixqa4rhssb2sc38zxgwg77j"

["github.com/bgentry/go-netrc"]
  sumVersion = "v0.0.0-20140422174119-9fd32a8b3d3d"
  ["github.com/bgentry/go-netrc".fetch]
    type = "git"
    url = "https://github.com/bgentry/go-netrc"
    rev = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
    sha256 = "0dn2h8avgavqdzdqnph8bkhj35bx0wssczry1zdczr22xv650g1l"

["github.com/cheggaaa/pb"]
  sumVersion = "v1.0.27"
  ["github.com/cheggaaa/pb".fetch]
    type = "git"
    url = "https://github.com/cheggaaa/pb"
    rev = "1cc5bbe20449079337944d56292c7383510c534c"
    sha256 = "1f995nsqgi0r4qc16nmxlbdxc536hkfwa5k9xb8ypz8d6jlkihag"

["github.com/client9/misspell"]
  sumVersion = "v0.3.4"
  ["github.com/client9/misspell".fetch]
    type = "git"
    url = "https://github.com/client9/misspell"
    rev = "b90dc15cfd220ecf8bbc9043ecb928cef381f011"
    sha256 = "1vwf33wsc4la25zk9nylpbp9px3svlmldkm0bha4hp56jws4q9cs"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/fatih/color"]
  sumVersion = "v1.7.0"
  ["github.com/fatih/color".fetch]
    type = "git"
    url = "https://github.com/fatih/color"
    rev = "5b77d2a35fb0ede96d138fc9a99f5c9b6aef11b4"
    sha256 = "0v8msvg38r8d1iiq2i5r4xyfx0invhc941kjrsg5gzwvagv55inv"

["github.com/golang/glog"]
  sumVersion = "v0.0.0-20160126235308-23def4e6c14b"
  ["github.com/golang/glog".fetch]
    type = "git"
    url = "https://github.com/golang/glog"
    rev = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
    sha256 = "0jb2834rw5sykfr937fxi8hxi2zy80sj2bdn9b3jb4b26ksqng30"

["github.com/golang/mock"]
  sumVersion = "v1.3.1"
  ["github.com/golang/mock".fetch]
    type = "git"
    url = "https://github.com/golang/mock"
    rev = "d74b93584564161b2de771089ee697f07d8bd5b5"
    sha256 = "1wnfa8njxdym1qb664dmfnkpm4pmqy22hqjlqpwaaiqhglb5g9d1"

["github.com/golang/protobuf"]
  sumVersion = "v1.3.2"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "6c65a5562fc06764971b7c5d05c76c75e84bdbf7"
    sha256 = "1k1wb4zr0qbwgpvz9q5ws9zhlal8hq7dmq62pwxxriksayl6hzym"

["github.com/google/btree"]
  sumVersion = "v1.0.0"
  ["github.com/google/btree".fetch]
    type = "git"
    url = "https://github.com/google/btree"
    rev = "4030bb1f1f0c35b30ca7009e9ebd06849dd45306"
    sha256 = "0ba430m9fbnagacp57krgidsyrgp3ycw5r7dj71brgp5r52g82p6"

["github.com/google/go-cmp"]
  sumVersion = "v0.3.0"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "6f77996f0c42f7b84e5a2b252227263f93432e9b"
    sha256 = "1hyxx3434zshl2m9ja78gwlkg1rx9yl6diqa7dnjb31xz5x4gbjj"

["github.com/google/martian"]
  sumVersion = "v2.1.0+incompatible"
  ["github.com/google/martian".fetch]
    type = "git"
    url = "https://github.com/google/martian"
    rev = "195b986b4b6d4c513582cf4d2b8c4fd7e2494f7e"
    sha256 = "197hil6vrjk50b9wvwyzf61csid83whsjj6ik8mc9r2lryxlyyrp"

["github.com/google/pprof"]
  sumVersion = "v0.0.0-20190515194954-54271f7e092f"
  ["github.com/google/pprof".fetch]
    type = "git"
    url = "https://github.com/google/pprof"
    rev = "54271f7e092ff31b10b7626fee166cbc6304e350"
    sha256 = "14x4ydifz23rzaylggvwbm3dwlv1bc6s0bclmkxck9nbjbqw89vy"

["github.com/googleapis/gax-go/v2"]
  sumVersion = "v2.0.5"
  relPath = "v2"
  ["github.com/googleapis/gax-go/v2".fetch]
    type = "git"
    url = "https://github.com/googleapis/gax-go"
    rev = "bd5b16380fd03dc758d11cef74ba2e3bc8b0e8c2"
    sha256 = "1lxawwngv6miaqd25s3ba0didfzylbwisd2nz7r4gmbmin6jsjrx"

["github.com/hashicorp/go-cleanhttp"]
  sumVersion = "v0.5.0"
  ["github.com/hashicorp/go-cleanhttp".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-cleanhttp"
    rev = "e8ab9daed8d1ddd2d3c4efba338fe2eeae2e4f18"
    sha256 = "1mwl96a815x1843pnqn7lk38s05bgn5rdjw57xd46jzr62izcnsq"

["github.com/hashicorp/go-getter"]
  sumVersion = "v1.4.1"
  ["github.com/hashicorp/go-getter".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-getter"
    rev = "0d2e82b049447fff51421fcfb85ee25016d2ced1"
    sha256 = "181r3i9z67baqd9k951i77py0kplsvx38bkqhpwinrv3q8v1a5c8"

["github.com/hashicorp/go-safetemp"]
  sumVersion = "v1.0.0"
  ["github.com/hashicorp/go-safetemp".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-safetemp"
    rev = "c9a55de4fe06c920a71964b53cfe3dd293a3c743"
    sha256 = "0gydks8bkq88adlzmv8qj3rvljx15j94c8lyrp88ji2jn6dvv643"

["github.com/hashicorp/go-version"]
  sumVersion = "v1.1.0"
  ["github.com/hashicorp/go-version".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-version"
    rev = "d40cf49b3a77bba84a7afdbd7f1dc295d114efb1"
    sha256 = "1ykh3jl5zj5a4irkgp5mq936bqkznmf9lp23qk741vh4r5874vi8"

["github.com/hashicorp/golang-lru"]
  sumVersion = "v0.5.1"
  ["github.com/hashicorp/golang-lru".fetch]
    type = "git"
    url = "https://github.com/hashicorp/golang-lru"
    rev = "7087cb70de9f7a8bc0a10c375cb0d2280a8edf9c"
    sha256 = "13f870cvk161bzjj6x41l45r5x9i1z9r2ymwmvm7768kg08zznpy"

["github.com/jmespath/go-jmespath"]
  sumVersion = "v0.0.0-20160202185014-0b12d6b521d8"
  ["github.com/jmespath/go-jmespath".fetch]
    type = "git"
    url = "https://github.com/jmespath/go-jmespath"
    rev = "0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74"
    sha256 = "1vv6hph8j6xgv7gwl9vvhlsaaqsm22sxxqmgmldi4v11783pc1ld"

["github.com/jstemmer/go-junit-report"]
  sumVersion = "v0.0.0-20190106144839-af01ea7f8024"
  ["github.com/jstemmer/go-junit-report".fetch]
    type = "git"
    url = "https://github.com/jstemmer/go-junit-report"
    rev = "af01ea7f8024089b458d804d5cdf190f962a9a0c"
    sha256 = "1lp3n94ris12hac02wi31f3whs88lcrzwgdg43a5j6cafg9p1d0s"

["github.com/mattn/go-colorable"]
  sumVersion = "v0.0.9"
  ["github.com/mattn/go-colorable".fetch]
    type = "git"
    url = "https://github.com/mattn/go-colorable"
    rev = "167de6bfdfba052fa6b2d3664c8f5272e23c9072"
    sha256 = "1nwjmsppsjicr7anq8na6md7b1z84l9ppnlr045hhxjvbkqwalvx"

["github.com/mattn/go-isatty"]
  sumVersion = "v0.0.4"
  ["github.com/mattn/go-isatty".fetch]
    type = "git"
    url = "https://github.com/mattn/go-isatty"
    rev = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c"
    sha256 = "0zs92j2cqaw9j8qx1sdxpv3ap0rgbs0vrvi72m40mg8aa36gd39w"

["github.com/mattn/go-runewidth"]
  sumVersion = "v0.0.4"
  ["github.com/mattn/go-runewidth".fetch]
    type = "git"
    url = "https://github.com/mattn/go-runewidth"
    rev = "3ee7d812e62a0804a7d0a324e0249ca2db3476d3"
    sha256 = "00b3ssm7wiqln3k54z2wcnxr3k3c7m1ybyhb9h8ixzbzspld0qzs"

["github.com/mitchellh/go-homedir"]
  sumVersion = "v1.0.0"
  ["github.com/mitchellh/go-homedir".fetch]
    type = "git"
    url = "https://github.com/mitchellh/go-homedir"
    rev = "ae18d6b8b3205b561c79e8e5f69bff09736185f4"
    sha256 = "0f0z0aa4wivk4z1y503dmnw0k0g0g403dly8i4q263gfshs82sbq"

["github.com/mitchellh/go-testing-interface"]
  sumVersion = "v1.0.0"
  ["github.com/mitchellh/go-testing-interface".fetch]
    type = "git"
    url = "https://github.com/mitchellh/go-testing-interface"
    rev = "6d0b8010fcc857872e42fc6c931227569016843c"
    sha256 = "1dl2js8di858bawg7dadlf1qjpkl2g3apziihjyf5imri3znyfpw"

["github.com/otiai10/copy"]
  sumVersion = "v1.2.0"
  ["github.com/otiai10/copy".fetch]
    type = "git"
    url = "https://github.com/otiai10/copy"
    rev = "c5f0361fe546fb0f4f26b13746afc8864ea7f6d9"
    sha256 = "1kbc1wwkhjxss522znbzldbaqvcwhaqsx7wr2rv7ss5jj4mbvc96"

["github.com/otiai10/curr"]
  sumVersion = "v1.0.0"
  ["github.com/otiai10/curr".fetch]
    type = "git"
    url = "https://github.com/otiai10/curr"
    rev = "88e2f2cffa0b5f13e90ee963a321bd1b2f715561"
    sha256 = "0fpw20adq2wff7l4c87zaavj9jra4d64a8bbjixiiv3bbarim987"

["github.com/otiai10/mint"]
  sumVersion = "v1.3.1"
  ["github.com/otiai10/mint".fetch]
    type = "git"
    url = "https://github.com/otiai10/mint"
    rev = "bef812dd30a0e7e65435fde5ef6a81277d78ca05"
    sha256 = "1p9rzmp8q23nx44lmv7imfp3b4n6va79snipmbvhkscijgy4sqps"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.6.1"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "f654a9112bbeac49ca2cd45bfbe11533c4666cf8"
    sha256 = "1yhiqqzjvi63pf01rgzx68gqkkvjx03fvl5wk30br5l6s81s090l"

["github.com/ulikunitz/xz"]
  sumVersion = "v0.5.5"
  ["github.com/ulikunitz/xz".fetch]
    type = "git"
    url = "https://github.com/ulikunitz/xz"
    rev = "590df8077fbcb06ad62d7714da06c00e5dd2316d"
    sha256 = "07mivr4aiw3b8qzwajsxyjlpbkf3my4xx23lv0yryc4pciam5lhy"

["go.opencensus.io"]
  sumVersion = "v0.22.0"
  ["go.opencensus.io".fetch]
    type = "git"
    url = "https://github.com/census-instrumentation/opencensus-go"
    rev = "9c377598961b706d1542bd2d84d538b5094d596e"
    sha256 = "05jr8gkr2w34i5wwki4zhl5ch0qrgi7cdgag5iy5gpxplhbrvbg9"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20190605123033-f99c8df09eb5"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "f99c8df09eb5bff426315721bfa5f16a99cad32c"
    sha256 = "0jwi6c6366999mnpzwx3a2kr7hzvdx97qfwiphx0r7cy0mpf28hf"

["golang.org/x/exp"]
  sumVersion = "v0.0.0-20190510132918-efd6b22b2522"
  ["golang.org/x/exp".fetch]
    type = "git"
    url = "https://go.googlesource.com/exp"
    rev = "efd6b22b2522a48712e1fd0b3c1ab34d243f5245"
    sha256 = "0ysahwb7p6y09izks4ca8nk2w414gmjxzz44l5rmadlvk3k66cgp"

["golang.org/x/image"]
  sumVersion = "v0.0.0-20190227222117-0694c2d4d067"
  ["golang.org/x/image".fetch]
    type = "git"
    url = "https://go.googlesource.com/image"
    rev = "0694c2d4d067f97ebef574d63a763ee8ab559da7"
    sha256 = "0v4rs4xpi7agbdzjw713mp7gzij8z89058s0yfj3276mzlns3zk4"

["golang.org/x/lint"]
  sumVersion = "v0.0.0-20190409202823-959b441ac422"
  ["golang.org/x/lint".fetch]
    type = "git"
    url = "https://go.googlesource.com/lint"
    rev = "959b441ac422379a43da2230f62be024250818b0"
    sha256 = "1mgcv5f00pkzsbwnq2y7vqvd1b4lr5a3s47cphh2qv4indfk7pck"

["golang.org/x/mobile"]
  sumVersion = "v0.0.0-20190312151609-d3739f865fa6"
  ["golang.org/x/mobile".fetch]
    type = "git"
    url = "https://go.googlesource.com/mobile"
    rev = "d3739f865fa66d07c1f506505c18aac71a8ead6e"
    sha256 = "079ck2dyikacnph9s5mf0hrjnqlk6lc8q64dwnyw45w3xbbc50mg"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190620200207-3b0461eec859"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "3b0461eec859c4b73bb64fdc8285971fd33e3938"
    sha256 = "0l00c8l0a8xnv6qdpwfzxxsr58jggacgzdrwiprrfx2xqm37b6d5"

["golang.org/x/oauth2"]
  sumVersion = "v0.0.0-20190604053449-0f29369cfe45"
  ["golang.org/x/oauth2".fetch]
    type = "git"
    url = "https://go.googlesource.com/oauth2"
    rev = "0f29369cfe4552d0e4bcddc57cc75f4d7e672a33"
    sha256 = "06jwpvx0x2gjn2y959drbcir5kd7vg87k0r1216abk6rrdzzrzi2"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20190423024810-112230192c58"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "112230192c580c3556b8cee6403af37a4fc5f28c"
    sha256 = "05i2k43j2d0llq768hg5pf3hb2yhfzp9la1w5wp0rsnnzblr0lfn"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20190624142023-c5567b49c5d0"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "c5567b49c5d04a5f83870795b8c0e2df43a8ce32"
    sha256 = "0z6nh1ma3jmqa0wh5dk9183kbm0sdzja5wl3mbnmimjv88f3rmah"

["golang.org/x/text"]
  sumVersion = "v0.3.2"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475"
    sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh"

["golang.org/x/time"]
  sumVersion = "v0.0.0-20190308202827-9d24e82272b4"
  ["golang.org/x/time".fetch]
    type = "git"
    url = "https://go.googlesource.com/time"
    rev = "9d24e82272b4f38b78bc8cff74fa936d31ccd8ef"
    sha256 = "1f5nkr4vys2vbd8wrwyiq2f5wcaahhpxmia85d1gshcbqjqf8dkb"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20190628153133-6cdbf07be9d0"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "6cdbf07be9d0ad08776df0b65fb1b3e4e617c42a"
    sha256 = "08nsarz53xbapsbdrj4kp05rli27zx6bmyb9f52hd739yi2375pv"

["google.golang.org/api"]
  sumVersion = "v0.9.0"
  ["google.golang.org/api".fetch]
    type = "git"
    url = "https://github.com/googleapis/google-api-go-client"
    rev = "feb0267beb8644f5088a03be4d5ec3f8c7020152"
    sha256 = "1lzdzkd2i41v6amxs9jah1q44qbvf1yvm8906jpfjiq6c3ffhqss"

["google.golang.org/appengine"]
  sumVersion = "v1.6.1"
  ["google.golang.org/appengine".fetch]
    type = "git"
    url = "https://github.com/golang/appengine"
    rev = "b2f4a3cf3c67576a2ee09e1fe62656a5086ce880"
    sha256 = "0zxlvwzxwkwz4bs4h9zc9979dx76y4xf9ks4d22bclg47dv59yry"

["google.golang.org/genproto"]
  sumVersion = "v0.0.0-20190819201941-24fa4b261c55"
  ["google.golang.org/genproto".fetch]
    type = "git"
    url = "https://github.com/googleapis/go-genproto"
    rev = "24fa4b261c55da65468f2abfdae2b024eef27dfb"
    sha256 = "109zhaqlfd8zkbr1hk6zqbs6vcxfrk64scjwh2nswph05gr0m84d"

["google.golang.org/grpc"]
  sumVersion = "v1.21.1"
  ["google.golang.org/grpc".fetch]
    type = "git"
    url = "https://github.com/grpc/grpc-go"
    rev = "501c41df7f472c740d0674ff27122f3f48c80ce7"
    sha256 = "0hla9rjvyi6wjak4cw39ic8jkdcd0lsymhrz9sa52bfybxsczf38"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/cheggaaa/pb.v1"]
  sumVersion = "v1.0.27"
  ["gopkg.in/cheggaaa/pb.v1".fetch]
    type = "git"
    url = "https://gopkg.in/cheggaaa/pb.v1"
    rev = "1cc5bbe20449079337944d56292c7383510c534c"
    sha256 = "1f995nsqgi0r4qc16nmxlbdxc536hkfwa5k9xb8ypz8d6jlkihag"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20200313102051-9f266ea9e77c"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "9f266ea9e77c4c7aab4cf02650570e7c7b3031a5"
    sha256 = "1bbai3lzb50m0x2vwsdbagrbhvfylj9k1m32hgbqwldqx4p9ay35"

["honnef.co/go/tools"]
  sumVersion = "v0.0.0-20190418001031-e561f6794a2a"
  ["honnef.co/go/tools".fetch]
    type = "git"
    url = "https://github.com/dominikh/go-tools"
    rev = "e561f6794a2a09dd97bd3cdefde08db0d564f55c"
    sha256 = "099mnjjkcw1jgqm6y1hjmqyi03a6f9asx7ifwp9c29c0yjw7fpd5"

["rsc.io/binaryregexp"]
  sumVersion = "v0.2.0"
  ["rsc.io/binaryregexp".fetch]
    type = "git"
    url = "https://github.com/rsc/binaryregexp"
    rev = "857b9542aaa89cfa42a1477b43fa1f24192fe921"
    sha256 = "1kar0myy85waw418zslviwx8846zj0m9cmqkxjx0fvgjdi70nc4b"
