name: Build and Check
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Nix ❄️
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Link Cachix 🔌
        uses: cachix/cachix-action@v10
        with:
          name: cosmos
          authToken: '${{ secrets.COSMOS_CACHE_KEY }}'

      - name: Check 🔎
        run: |
          nix flake check

      - name: Run Shell 🐚
        run: |
          nix develop

      - name: Build All 🛠️
        run: |
          nix build .#hermes
          nix build .#gaia
          nix build .#gm
          nix build .#cosmovisor
